/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ef3M4VY6Pls
 */
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Checkbox } from "@/components/ui/checkbox"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function NewUser() {
  return (
    <Card key="1" className="w-full max-w-2xl mx-auto space-y-8 p-6 bg-gray-400">
      <CardHeader>
        <CardTitle className="text-3xl font-bold text-center">New Software Engineer</CardTitle>
        <CardDescription className="text-center text-blue-600">
          Please fill in the form below with your details
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        <div className="space-y-2">
          <Label htmlFor="name">Full Name</Label>
          <Input id="name" placeholder="Enter your full name" required />
        </div>
        <div className="space-y-2">
          <Label htmlFor="email">Email</Label>
          <Input id="email" placeholder="Enter your email" required type="email" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="password">Password</Label>
          <Input id="password" placeholder="Enter your password" required type="password" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="languages">Programming Languages</Label>
          <div className="flex flex-col space-y-2">
            <div className="flex items-center space-x-2">
              <Checkbox id="python" />
              <Label htmlFor="python">Python</Label>
            </div>
            <div className="flex items-center space-x-2">
              <Checkbox id="javascript" />
              <Label htmlFor="javascript">JavaScript</Label>
            </div>
            <div className="flex items-center space-x-2">
              <Checkbox id="cpp" />
              <Label htmlFor="cpp">C++</Label>
            </div>
            <div className="flex items-center space-x-2">
              <Checkbox id="java" />
              <Label htmlFor="java">Java</Label>
            </div>
            <div className="flex items-center space-x-2">
              <Checkbox id="ruby" />
              <Label htmlFor="ruby">Ruby</Label>
            </div>
            <div className="flex items-center space-x-2">
              <Checkbox id="golang" />
              <Label htmlFor="golang">GoLang</Label>
            </div>
          </div>
        </div>
        <div className="space-y-2">
          <Label htmlFor="experience">Experience Level</Label>
          <div className="flex space-x-4">
            <div>
              <input id="junior" name="experience" type="radio" value="Junior" />
              <label htmlFor="junior">Junior</label>
            </div>
            <div>
              <input id="intermediate" name="experience" type="radio" value="Intermediate" />
              <label htmlFor="intermediate">Intermediate</label>
            </div>
            <div>
              <input id="senior" name="experience" type="radio" value="Senior" />
              <label htmlFor="senior">Senior</label>
            </div>
          </div>
        </div>
        <div className="space-y-2">
          <Label htmlFor="resume">Upload Resume</Label>
          <Input id="resume" required type="file" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="github">GitHub Profile</Label>
          <Input id="github" placeholder="Enter your GitHub profile URL" type="url" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="linkedin">LinkedIn Profile</Label>
          <Input id="linkedin" placeholder="Enter your LinkedIn profile URL" type="url" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="about-me">About Me</Label>
          <Textarea className="min-h-[100px]" id="about-me" placeholder="Tell us about yourself and your skills" />
        </div>
      </CardContent>
      <CardFooter>
        <Button className="w-full">Submit</Button>
      </CardFooter>
    </Card>
  )
}
